### ISSUE TITLE
link for 'Quality Metrics for Information Visualization'

### ISSUE THREAD

**Issue by andreibosco** [jamesscottbrown/open-access-eurovis#10]
- Paper title: Quality Metrics for Information Visualization
- First author: M. Behrisch
- URL: https://vcg.seas.harvard.edu/publications/quality-metrics-for-information-visualization/paper
- DOI: 10.1111/cgf.13446
- Abstract: The visualization community has developed to date many intuitions and understandings of how to judge the quality of views in visualizing data. The computation of a visualization’s quality and usefulness ranges from measuring clutter and overlap, up to the existence and perception of specific (visual) patterns. This survey attempts to report, categorize and unify the diverse understandings and aims to establish a common vocabulary that will enable a wide audience to understand their differences and subtleties. For this purpose, we present a commonly applicable quality metric formalization that should detail and relate all constituting parts of a quality metric. We organize our corpus of reviewed research papers along the data types established in the information visualization community: multi- and high-dimensional, relational, sequential, geospatial and text data. For each data type, we select the visualization subdomains in which quality metrics are an active research field and report their findings,reason on the underlying concepts, describe goals and outline the constraints and requirements. One central goal of this survey is to provide guidance on future research opportunities for the field and outline how different visualization communities could benefit from each other by applying or transferring knowledge to their respective subdomain. Additionally, we aim to motivate the visualization community to compare computed measures to the perception of humans.

**Comment by jamesscottbrown** [comment]
Thank you for providing this link.

However, in order to encourage authors to post preprints early, this repository (like Steve Haroz's [open access VIS](https://github.com/steveharoz/open-access-vis) repo) only provides links for those papers for which a preprint PDF was made available *before* the conference at which it was presented. I do not think that this was the case for this paper.
