### ISSUE TITLE
Data for "Bridging the Data Analysis Communication Gap Utilizing a Three-Component Summarized Line Graph" by C. Yau et al.

### ISSUE THREAD

**Issue by yauc** [jamesscottbrown/open-access-eurovis#2]
Data for Bridging the Data Analysis Communication Gap Utilizing a Three-Component Summarized Line Graph by Calvin Yau et al. can be found here: 
https://osf.io/pc95u/?view_only=698921410de24da3b776a18efc459642

A thumbnail is also attached: 

![EuroVis19 - Bridging the Data Analysis Communication Gap Utilizing a Three-Component Summarized Line Graph - Thumbnail](https://user-images.githubusercontent.com/11788343/58044402-a6847280-7b0d-11e9-96df-59fa1469258c.png)

**Comment by jamesscottbrown** [comment]
Thanks - I have added the links. I will add the thumbnail shortly, in a batch with several others.
