### ISSUE TITLE
Data for "InsideInsights: Integrating Data-Driven Reporting in Collaborative Visual Analytics"

### ISSUE THREAD

**Issue by 90am** [jamesscottbrown/open-access-eurovis#3]
Data for "InsideInsights: Integrating Data-Driven Reporting in Collaborative Visual Analytics" by A. Mathisen et al.

The paper can be found at https://pure.au.dk/portal/files/153734526/InsideInsights_EuroVis_.pdf.

The accompanying video is at https://vimeo.com/337474793.

 And the thumbnail is attached.
![insideinsights-thumbnail](https://user-images.githubusercontent.com/5486392/58091409-cbd6b680-7bc9-11e9-87a3-d50f4fb8a4cd.png)

**Comment by jamesscottbrown** [comment]
Thanks.
