### ISSUE TITLE
Info for "A Random Sampling O(n) Force-calculation Algorithm for Graph Layouts" by R. Gove

### ISSUE THREAD

**Issue by rpgove** [jamesscottbrown/open-access-eurovis#4]
Thanks for maintaining this site! Here is some updated info for this paper.

AuthorPDF: https://osf.io/2vpe4/

Data: https://osf.io/nb7m8/

SourceMaterials: https://osf.io/nb7m8/

ExplanationPage: https://www.twosixlabs.com/graph-layout-by-random-vertex-sampling/

Abstract: This paper proposes a linear-time repulsive-force-calculation algorithm with sub-linear auxiliary space requirements, achieving an asymptotic improvement over the Barnes-Hut and Fast Multipole Method force-calculation algorithms. The algorithm, named random vertex sampling (RVS), achieves its speed by updating a random sample of vertices at each iteration, each with a random sample of repulsive forces. This paper also proposes a combination algorithm that uses RVS to derive an initial layout and then applies Barnes-Hut to refine the layout. An evaluation of RVS and the combination algorithm compares their speed and quality on 109 graphs against a Barnes-Hut layout algorithm. The RVS algorithm performs up to 6.1 times faster on the tested graphs while maintaining comparable layout quality. The combination algorithm also performs faster than Barnes-Hut, but produces layouts that are more symmetric than using RVS alone. Data and code: https://osf.io/nb7m8/

**Comment by jamesscottbrown** [comment]
Thanks.
